version: '3.3'
services:
  database:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ~/data/db:/data/db
    networks:
      - webapp-network
  backend:
    image: x-mind/backend
    restart: always
    depends_on:
      - database
    ports:
      - 8800:8800
    networks:
      - webapp-network
  frontend:
    image: x-mind/frontend
    restart: always
    depends_on:
      - backend
      - database
    ports:
      - 4000:80
    networks:
      - webapp-network
networks:
  webapp-network:
    driver: bridge
